### ISSUE TITLE
Default configuration for next js needs to be updated

### ISSUE THREAD

**Issue by AJHassall** [actions/configure-pages#109]
I think the change from the command 'next export' to "output: export" in next.config.js has broken the default configuration

this doesnt work
```
      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
               static_site_generator: next
```
this does
```
      - name: Setup Pages
        uses: actions/configure-pages@v3
```
I have set up my own next config.

I spent some time trying to find out what was breaking my page so I thought I would pass this on so someone else doesnt have to
